# Automated Data Quality & KPI Drift Monitor for `test_df`
# Generated by DeepAnalyze Autonomous EDA Engine (2026-08-29 03:16)

import polars as pl
import sys

def audit_dataset(df_path: str):
    """Runs automated quality gates and null drift checks on test_df."""
    print(f"[Monitoring]: Ingesting {df_path}...")
    try:
        df = pl.read_csv(df_path) if df_path.endswith(".csv") else pl.read_parquet(df_path)
    except Exception as e:
        print(f"❌ Ingestion check failed: {e}")
        sys.exit(1)

    print(f"✔ Row count: {df.height:,} rows, {df.width} columns")

    # 1. Null Surge Assertions (< 10% nulls per critical column)
    null_counts = df.null_count().row(0)
    for idx, col in enumerate(df.columns):
        null_pct = (null_counts[idx] / df.height) * 100 if df.height > 0 else 0
        if null_pct > 10.0:
            print(f"⚠ [ALERT]: Column '{col}' has {null_pct:.1f}% missing values (> 10% threshold).")

    # 2. Schema Integrity Checks
    expected_cols = ['customer_name', 'amount', 'category']
    missing_cols = [c for c in expected_cols if c not in df.columns]
    if missing_cols:
        print(f"❌ [CRITICAL]: Missing expected schema columns: {missing_cols}")
        sys.exit(1)

    print("✅ All Data Quality Gates & Invariants passed successfully.")

if __name__ == "__main__":
    if len(sys.argv) > 1:
        audit_dataset(sys.argv[1])
    else:
        print("Usage: python eda_quality_monitor.py <dataset_path>")
