#!/usr/bin/env python3
"""Automated Production Data Pipeline for `test_df`.
Generated by DeepAnalyze v3.0 Production Compiler.
Timestamp: 2026-08-29 03:57:51
"""

import argparse
import sys
import os
import polars as pl

def run_pipeline(input_path: str, output_path: str = None) -> pl.DataFrame:
    """Executes optimized zero-copy Polars ETL sequence on source dataset."""
    print(f"📥 [ETL Ingestion]: Scanning {input_path}...")
    if not os.path.exists(input_path):
        raise FileNotFoundError(f"Input file not found: {input_path}")

    if input_path.endswith(".csv"):
        df = pl.read_csv(input_path, infer_schema_length=10000, ignore_errors=True)
    elif input_path.endswith((".xlsx", ".xls")):
        df = pl.read_excel(input_path)
    elif input_path.endswith((".parquet", ".pq")):
        df = pl.read_parquet(input_path)
    else:
        df = pl.read_csv(input_path, ignore_errors=True)

    print(f"✔ Ingested {df.height:,} records across {df.width} columns.")

    # =========================================================================
    # PRODUCTION TRANSFORMATION LINEAGE
    # =========================================================================
    # Clean & normalize schema
    # 1. Clean string whitespace and normalize column identifiers
    clean_cols = [c.strip().replace(" ", "_").lower() for c in df.columns]
    df = df.rename(dict(zip(df.columns, clean_cols)))

    # 2. Assert dtypes and strip null bursts
    df = df.filter(~pl.all_horizontal(pl.all().is_null()))

    print(f"🚀 Pipeline transformation complete: {df.height:,} curated records.")

    if output_path:
        print(f"💾 Saving curated parquet output to: {output_path}")
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        df.write_parquet(output_path, compression="zstd")

    return df

def main():
    parser = argparse.ArgumentParser(description="DeepAnalyze Production Pipeline Runner")
    parser.add_argument("--input", "-i", type=str, required=True, help="Path to input raw data file")
    parser.add_argument("--output", "-o", type=str, default="./output_curated.parquet", help="Destination path for parquet output")
    args = parser.parse_args()

    try:
        run_pipeline(args.input, args.output)
        print("✅ Pipeline executed successfully with zero runtime errors.")
    except Exception as e:
        print(f"❌ Pipeline failed: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
