"""Unit tests for DeepAnalyze Profiler: Deep Data Exploration, Workbook Topology & Engineering Briefing."""

import polars as pl
import pytest
from deepanalyze.profiler import (
    ColumnProfile,
    ForeignKeyCandidate,
    SheetProfile,
    SheetRole,
    WorkbookTopology,
    detect_accounting_negatives,
    detect_date_formats,
    detect_dirty_currency,
    detect_foreign_keys,
    detect_sheet_role,
    detect_whitespace_issues,
    generate_engineering_briefing,
    infer_column_role,
    profile_dataframe,
)


def test_detect_date_formats():
    samples_iso = ["2025-01-15", "2025-02-20", "2025-03-01"]
    fmts = detect_date_formats(samples_iso)
    assert any("YYYY-MM-DD" in f for f in fmts)

    samples_mixed = ["15/08/2025", "2025-08-15", "15-Aug-2025", "August 15, 2025"]
    mixed_fmts = detect_date_formats(samples_mixed)
    assert len(mixed_fmts) >= 3


def test_detect_accounting_negatives():
    samples_with_neg = ["1,250.00", "(500.00)", "75.50", "(SAR 1,000.00)"]
    assert detect_accounting_negatives(samples_with_neg) is True

    samples_trailing_minus = ["100.00", "250.00-", "50.00"]
    assert detect_accounting_negatives(samples_trailing_minus) is True

    clean_samples = ["1,250.00", "-500.00", "75.50"]
    assert detect_accounting_negatives(clean_samples) is False


def test_detect_dirty_currency():
    samples_curr = ["$100.50", "€45.00", "SAR 250", "£12.99"]
    assert detect_dirty_currency(samples_curr) is True

    clean_numbers = ["100.50", "45.00", "250", "12.99"]
    assert detect_dirty_currency(clean_numbers) is False


def test_detect_whitespace_issues():
    samples_ws = [" Riyadh", "Jeddah ", "Dammam\t", "Khobar\u00a0"]
    assert detect_whitespace_issues(samples_ws) is True

    clean_samples = ["Riyadh", "Jeddah", "Dammam", "Khobar"]
    assert detect_whitespace_issues(clean_samples) is False


def test_infer_column_role():
    assert infer_column_role("id", 1.0, "Int64", 0.0, ["1", "2", "3"]) == "Primary Key Candidate"
    assert infer_column_role("customer_age", 0.05, "Int64", 0.0, ["25", "30"]) == "Quasi-Identifier"
    assert infer_column_role("dept_code", 0.02, "String", 0.0, ["D1", "D2"]) == "Business Key / Foreign Identifier"
    assert infer_column_role("sales_amount", 0.8, "Float64", 0.0, ["100.5", "200.0"]) == "Numeric Metric / Quantitative"
    assert infer_column_role(
        "clinical_notes", 0.9, "String", 0.0,
        ["Patient presented with high fever and reported shortness of breath."]
    ) == "Free-Text Narrative / Clinical Note"


def test_profile_dataframe():
    df = pl.DataFrame({
        "tx_id": ["T1", "T2", "T3", "T4"],
        "date_str": ["2025-01-01", "15/02/2025", "2025-03-01", "10-Apr-2025"],
        "balance": ["1,000.00", "(250.00)", "$500.00", " SAR 300 "],
        "category": ["A", "B", "A", "B"],
    })

    profile = profile_dataframe(df, name="test_sheet")
    assert profile.sheet_name == "test_sheet"
    assert profile.row_count == 4
    assert profile.col_count == 4
    assert profile.role in (SheetRole.TRANSACTION_LEDGER, SheetRole.LOOKUP_DIMENSION)

    col_map = {c.name: c for c in profile.columns}
    assert col_map["balance"].has_accounting_negatives is True
    assert col_map["balance"].has_dirty_currency is True
    assert col_map["balance"].has_whitespace_issues is True
    assert len(col_map["date_str"].date_formats) >= 2


def test_detect_sheet_role_pivot():
    pivot_df = pl.DataFrame({
        "Department": ["Sales", "Engineering", "Total"],
        "jan": [100, 200, 300],
        "feb": [150, 250, 400],
        "mar": [180, 280, 460],
    })
    role, offset, subtotal_rows = detect_sheet_role(pivot_df, "Quarterly_Summary")
    assert role == SheetRole.PIVOT_TABLE
    assert 2 in subtotal_rows  # Row 2 contains "Total"


def test_detect_sheet_role_lookup():
    lookup_df = pl.DataFrame({
        "dept_code": ["D01", "D02", "D03"],
        "dept_name": ["Finance", "HR", "Legal"],
        "cost_center": [1001, 1002, 1003],
    })
    role, offset, subtotal_rows = detect_sheet_role(lookup_df, "dim_departments")
    assert role == SheetRole.LOOKUP_DIMENSION


def test_detect_sheet_role_metadata_block():
    meta_df = pl.DataFrame({
        "Report Name": ["Sales Summary"],
        "Generated By": ["ERP Admin"],
        "Date": ["2025-08-15"],
    })
    role, offset, subtotal_rows = detect_sheet_role(meta_df, "Cover")
    assert role == SheetRole.METADATA_BLOCK


def test_detect_foreign_keys():
    df1 = pl.DataFrame({
        "order_id": [1, 2, 3, 4],
        "cust_id": ["C100", "C101", "C102", "C103"],
        "amount": [50.0, 60.0, 70.0, 80.0],
    })
    df2 = pl.DataFrame({
        "cust_id": ["C100", "C101", "C102", "C104"],
        "cust_name": ["Alpha", "Beta", "Gamma", "Delta"],
    })

    p1 = profile_dataframe(df1, name="Orders")
    p2 = profile_dataframe(df2, name="Customers")

    candidates = detect_foreign_keys({"Orders": p1, "Customers": p2})
    assert len(candidates) >= 1
    fk = candidates[0]
    assert fk.from_col == "cust_id"
    assert fk.to_col == "cust_id"
    assert fk.overlap_pct >= 75.0


def test_generate_engineering_briefing():
    df1 = pl.DataFrame({
        "order_id": [1, 2, 3],
        "cust_id": ["C1", "C2", "C3"],
        "amount": ["$100.00", "(50.00)", " SAR 200 "],
        "date": ["2025-01-01", "02/02/2025", "15-Mar-2025"],
    })
    p1 = profile_dataframe(df1, name="Orders")

    topology = WorkbookTopology(
        file_path="mock_orders.xlsx",
        sheets={"Orders": p1},
        primary_sheet="Orders",
        foreign_keys=[],
        recommended_pipeline_steps=["Clean dirty currency and accounting negatives in `amount`."]
    )

    briefing = generate_engineering_briefing(topology, user_prompt="Consolidate and clean sales ledger")
    assert "AUTONOMOUS DATA ENGINEERING & TOPOLOGY BRIEFING" in briefing
    assert "Orders" in briefing
    assert "Mixed date formats" in briefing
    assert "accounting negative brackets" in briefing
    assert "Clean dirty currency" in briefing
