"""DeepAnalyze v4.0 AST Security Firewall & Watchdog Guard.

Inspects incoming Python / Polars code generated by external AI before execution,
enforcing strict prohibitions against unauthorized network calls, env var extraction,
filesystem tampering, dynamic execution, and reflection attacks.
Maintains a 5-level in-memory LIFO rollback snapshot stack for instant undo.
Provides pipeline file generation for .py and .ipynb airlock runs.
"""

import ast
from collections import defaultdict
import copy
from dataclasses import dataclass
import json
import os
import signal
import sys
import threading
import time
from typing import Any, Dict, List, Optional, Set, Tuple

import polars as pl


class ASTSecurityViolation(PermissionError):
    """Raised when incoming code violates the AST security boundary."""
    pass


class OverCleaningViolation(ValueError):
    """Raised when an incoming transformation script causes catastrophic data loss or over-cleans records."""
    pass


class ASTFirewallVisitor(ast.NodeVisitor):
    """AST visitor that detects forbidden module imports, function calls, and attribute access."""

    FORBIDDEN_MODULES: Set[str] = {
        "socket", "requests", "urllib", "httpx", "aiohttp", "paramiko",
        "ftplib", "telnetlib", "smtplib", "poplib", "imaplib", "http",
        "subprocess", "shutil", "posix", "pty", "commands"
    }

    FORBIDDEN_CALLS: Set[str] = {
        "eval", "exec", "compile", "__import__", "open", "getattr", "setattr", "delattr"
    }

    FORBIDDEN_OS_ATTRS: Set[str] = {
        "system", "popen", "spawn", "fork", "kill", "remove", "unlink",
        "rmdir", "removedirs", "chmod", "chown", "truncate", "environ", "getenv"
    }

    FORBIDDEN_DUNDERS: Set[str] = {
        "__subclasses__", "__globals__", "__code__", "__builtins__", "__dict__", "__class__"
    }

    SENSITIVE_PATHS: Set[str] = {
        "/etc/passwd", "/etc/shadow", "/etc/sudoers", "~/.ssh", "~/.aws",
        "~/.gemini", "~/.bashrc", "~/.zshrc", "/root", "/var/log"
    }

    FORBIDDEN_PATHLIB_METHODS: Set[str] = {
        "write_text", "write_bytes", "unlink", "rmdir", "chmod", "lchmod"
    }

    def __init__(self):
        super().__init__()
        self.violations: List[str] = []

    def visit_Constant(self, node: ast.Constant) -> None:
        if isinstance(node.value, str):
            val_lower = node.value.lower()
            for path in self.SENSITIVE_PATHS:
                if path in val_lower:
                    self.violations.append(f"Forbidden sensitive path access in script constant: '{node.value}'")
        self.generic_visit(node)

    def visit_Import(self, node: ast.Import) -> None:
        for alias in node.names:
            root_module = alias.name.split(".")[0]
            if root_module in self.FORBIDDEN_MODULES:
                self.violations.append(f"Forbidden module import: `{alias.name}`")
        self.generic_visit(node)

    def visit_ImportFrom(self, node: ast.ImportFrom) -> None:
        if node.module:
            root_module = node.module.split(".")[0]
            if root_module in self.FORBIDDEN_MODULES:
                self.violations.append(f"Forbidden from-import: `{node.module}`")
            if root_module == "os":
                for alias in node.names:
                    if alias.name in self.FORBIDDEN_OS_ATTRS:
                        self.violations.append(f"Forbidden os attribute import: `os.{alias.name}`")
        self.generic_visit(node)

    def visit_Call(self, node: ast.Call) -> None:
        if isinstance(node.func, ast.Name):
            if node.func.id in self.FORBIDDEN_CALLS:
                self.violations.append(f"Forbidden direct function call: `{node.func.id}()`")

        elif isinstance(node.func, ast.Attribute):
            attr_name = node.func.attr
            if attr_name in self.FORBIDDEN_DUNDERS:
                self.violations.append(f"Forbidden dunder attribute invocation: `.{attr_name}`")
            if attr_name in self.FORBIDDEN_PATHLIB_METHODS:
                self.violations.append(f"Forbidden filesystem alteration via pathlib: `.{attr_name}()`")
            if attr_name == "sleep" and isinstance(node.func.value, ast.Name) and node.func.value.id == "time":
                if node.args and isinstance(node.args[0], ast.Constant) and isinstance(node.args[0].value, (int, float)):
                    if node.args[0].value > 1.0:
                        self.violations.append(f"Forbidden side-channel timing delay: `time.sleep({node.args[0].value})` exceeds 1.0s limit")
            if isinstance(node.func.value, ast.Name) and node.func.value.id == "os":
                if attr_name in self.FORBIDDEN_OS_ATTRS:
                    self.violations.append(f"Forbidden OS call: `os.{attr_name}()`")

        self.generic_visit(node)

    def visit_Attribute(self, node: ast.Attribute) -> None:
        if node.attr in self.FORBIDDEN_DUNDERS:
            self.violations.append(f"Forbidden dunder reflection: `.{node.attr}`")
        if isinstance(node.value, ast.Name) and node.value.id == "os":
            if node.attr in self.FORBIDDEN_OS_ATTRS:
                self.violations.append(f"Forbidden OS attribute access: `os.{node.attr}`")
        self.generic_visit(node)


def audit_code(code_str: str) -> bool:
    """Performs pre-execution static AST analysis.

    Raises ASTSecurityViolation if any forbidden patterns are discovered.
    """
    if not code_str or not code_str.strip():
        return True

    try:
        tree = ast.parse(code_str)
    except SyntaxError as err:
        raise SyntaxError(f"AST Parse Error in script: {err}")

    visitor = ASTFirewallVisitor()
    visitor.visit(tree)

    if visitor.violations:
        violation_summary = "\n- " + "\n- ".join(visitor.violations)
        raise ASTSecurityViolation(
            f"AST Security Violation Detected! The incoming code was blocked:\n{violation_summary}"
        )

    return True


# =============================================================================
# WATCHDOG & SECURE EXECUTION
# =============================================================================

def prepare_dataframe_for_code(df: Any, code_str: str) -> Tuple[Any, str]:
    """Auto-converts DataFrame between Pandas and Polars based on code dialect."""
    if df is None:
        return None, "none"

    code_lower = code_str.lower()
    has_polars_markers = any(k in code_lower for k in [
        "pl.", "polars", "with_columns", "pl.col", ".filter(pl.", ".select(pl."
    ])
    has_pandas_markers = any(k in code_lower for k in [
        "pd.", "pandas", "np.", "numpy", ".iloc", ".loc", ".apply(",
        ".ffill(", ".bfill(", ".reset_index(", "axis=", ".dropna(", ".fillna(",
        ".groupby(", ".drop(columns=", ".to_datetime("
    ]) or ("[" in code_str and "]" in code_str and not has_polars_markers)

    if has_pandas_markers and not has_polars_markers:
        if hasattr(df, "to_pandas"):
            try:
                return df.to_pandas(), "pandas"
            except Exception:
                pass
        return df, "pandas"
    elif has_polars_markers:
        if hasattr(df, "to_dict") and not isinstance(df, pl.DataFrame):
            try:
                return pl.from_pandas(df), "polars"
            except Exception:
                pass
        return df, "polars"
    else:
        # If code uses standard Pandas dataframe operations, default to pandas if already pandas
        return df, "pandas" if hasattr(df, "iloc") else "polars"


def execute_code_safely(
    code_str: str,
    global_scope: Dict[str, Any],
    timeout_sec: float = 15.0
) -> Dict[str, Any]:
    """Audits code and executes it within local RAM with a watchdog timer.

    Pre-injects pandas (pd), numpy (np), and polars (pl) to guarantee compatibility
    with external AI-generated transformation pipelines. Sets __name__ to '__main__'
    so script-style execution blocks execute naturally.
    """
    audit_code(code_str)

    # Set __name__ to __main__ so cloud AI 'if __name__ == "__main__":' blocks execute
    global_scope.setdefault("__name__", "__main__")

    # Pre-inject core data science and utility libraries expected by cloud AI code
    global_scope.setdefault("copy", copy)
    import re
    global_scope.setdefault("re", re)
    global_scope.setdefault("pl", pl)
    try:
        import pandas as pd
        global_scope.setdefault("pd", pd)
    except ImportError:
        pass
    try:
        import numpy as np
        global_scope.setdefault("np", np)
    except ImportError:
        pass

    exec_exception = None
    exec_completed = False

    def _target():
        nonlocal exec_exception, exec_completed
        try:
            exec(code_str, global_scope)
            exec_completed = True
        except Exception as e:
            exec_exception = e

    worker = threading.Thread(target=_target, daemon=True)
    worker.start()
    worker.join(timeout=timeout_sec)

    if worker.is_alive():
        raise TimeoutError(
            f"Script execution aborted: Execution exceeded watchdog timeout of {timeout_sec} seconds."
        )

    if exec_exception:
        raise exec_exception

    return global_scope


def resolve_transformed_dataframe(
    global_scope: Dict[str, Any],
    original_df: Any,
    primary_var: str = "df",
    input_path: Optional[str] = None
) -> Tuple[Any, str]:
    """Inspects execution scope, created files, and defined functions to harvest the transformed DataFrame.

    Handles:
    1. Output files created/modified on disk (OUTPUT_FILE, output_path, etc.)
    2. Explicitly assigned DataFrame variables (cleaned_df, df_clean, final_df, df, etc.)
    3. In-place modified DataFrames
    4. Callable pipeline functions (clean_*, transform_*, process_*, etc.)
    """
    import inspect
    try:
        import pandas as pd
    except ImportError:
        pd = None

    # 1. Check if output file was written to disk
    for key in ["OUTPUT_FILE", "output_path", "output_file", "clean_out_path", "OUTPUT_PATH"]:
        out_path = global_scope.get(key)
        if out_path and isinstance(out_path, str) and os.path.isfile(out_path) and pd is not None:
            try:
                if out_path.endswith(".csv"):
                    return pd.read_csv(out_path), f"output file `{os.path.basename(out_path)}`"
                elif out_path.endswith((".xlsx", ".xls")):
                    return pd.read_excel(out_path), f"output file `{os.path.basename(out_path)}`"
                elif out_path.endswith(".parquet"):
                    return pd.read_parquet(out_path), f"output file `{os.path.basename(out_path)}`"
            except Exception:
                pass

    # 2. Check candidate DataFrame variables in scope
    candidate_vars = [
        "df_cleaned", "cleaned_df", "df_clean", "clean_df", "final_df",
        "df_transformed", "transformed_df", "result_df", "result",
        "df_out", "out_df", "data_clean", "cleaned_data",
        "df", primary_var, "data"
    ]
    for var in candidate_vars:
        if var in global_scope:
            val = global_scope[var]
            if (pd is not None and isinstance(val, pd.DataFrame)) or isinstance(val, pl.DataFrame):
                if val is not original_df:
                    return val, f"variable `{var}`"
                if hasattr(val, "shape") and hasattr(original_df, "shape"):
                    if val.shape != original_df.shape:
                        return val, f"in-place modified `{var}`"
            elif isinstance(val, dict):
                # Handle multi-sheet dicts returned e.g. from pd.read_excel(..., sheet_name=None)
                if primary_var in val and ((pd is not None and isinstance(val[primary_var], pd.DataFrame)) or isinstance(val[primary_var], pl.DataFrame)):
                    return val[primary_var], f"sheet `{primary_var}` from dict `{var}`"
                for s_key, s_df in val.items():
                    if (pd is not None and isinstance(s_df, pd.DataFrame)) or isinstance(s_df, pl.DataFrame):
                        return s_df, f"sheet `{s_key}` from dict `{var}`"

    # 3. Check for callable transformation functions defined in scope
    for name, obj in list(global_scope.items()):
        if callable(obj) and not inspect.isclass(obj):
            lname = name.lower()
            if any(term in lname for term in ["clean", "transform", "process", "normalize", "unpivot", "flatten", "pipeline"]):
                try:
                    sig = inspect.signature(obj)
                    params = list(sig.parameters.values())
                    if params:
                        first_param = params[0].name.lower()
                        if any(p in first_param for p in ["path", "file", "csv", "xlsx", "input"]):
                            if input_path and os.path.isfile(input_path):
                                res = obj(input_path)
                                if (pd is not None and isinstance(res, pd.DataFrame)) or isinstance(res, pl.DataFrame):
                                    return res, f"function `{name}(input_path)`"
                        else:
                            res = obj(original_df)
                            if (pd is not None and isinstance(res, pd.DataFrame)) or isinstance(res, pl.DataFrame):
                                return res, f"function `{name}(df)`"
                except Exception:
                    pass

    return original_df, "unmodified original"


def audit_transformation_safety(
    raw_df: Any,
    transformed_df: Any,
    arch_key: str = "CLEAN_TABULAR",
    strict: bool = True
) -> Tuple[bool, str]:
    """Audits transformation results against the raw dataset for catastrophic data loss,

    destructive over-filtering, and financial/volumetric conservation breaches.
    Works dynamically and agnostically across all dataset architectures.
    """
    if raw_df is None or transformed_df is None:
        return True, "Null dataset bypassed safety audit."

    try:
        import pandas as pd
    except ImportError:
        pd = None

    # 1. Zero-Row / Empty DataFrame Fatal Check
    transformed_rows = transformed_df.height if hasattr(transformed_df, "height") else (
        transformed_df.shape[0] if hasattr(transformed_df, "shape") else len(transformed_df)
    )
    raw_rows = raw_df.height if hasattr(raw_df, "height") else (
        raw_df.shape[0] if hasattr(raw_df, "shape") else len(raw_df)
    )

    if raw_rows > 0 and transformed_rows == 0:
        raise OverCleaningViolation(
            "Over-Cleaning Fatal Error: Transformed DataFrame is completely empty (0 rows)! "
            "The transformation script discarded 100% of records."
        )

    # If raw dataset is small (<= 5 rows), bypass retention ratio check
    if raw_rows <= 5:
        return True, "Small dataset passed safety audit."

    # 2. Volumetric Retention & Over-Filtering Analysis
    retention_ratio = transformed_rows / raw_rows

    if arch_key == "ERP_RAGGED":
        expected_line_items = None
        try:
            from .erp_cleaner import sniff_erp_layout
            schema = sniff_erp_layout(raw_df)
            pdf = raw_df.to_pandas() if hasattr(raw_df, "to_pandas") else raw_df
            seq_count = 0
            if 0 <= schema.doc_col < pdf.shape[1]:
                series = pdf.iloc[:, schema.doc_col].dropna().astype(str).str.strip()
                for v in series:
                    try:
                        val_num = float(v)
                        if val_num >= 1000 or (val_num.is_integer() and 1 <= val_num <= 5000):
                            seq_count += 1
                    except ValueError:
                        pass
            if seq_count >= 5:
                expected_line_items = seq_count
        except Exception:
            pass

        if expected_line_items is not None and expected_line_items > 0:
            line_retention = transformed_rows / expected_line_items
            if line_retention < 0.4:
                raise OverCleaningViolation(
                    f"Over-Cleaning Violation: Transformed dataset retained only {transformed_rows} rows out of "
                    f"~{expected_line_items} expected line items ({line_retention*100:.1f}% line retention). "
                    f"Blind dropna() or destructive over-filtering detected in hierarchical ERP dataset."
                )
        else:
            if retention_ratio < 0.08 and transformed_rows < 15:
                raise OverCleaningViolation(
                    f"Over-Cleaning Violation: Transformed dataset retained only {transformed_rows} rows out of "
                    f"{raw_rows} raw rows ({retention_ratio*100:.1f}% retention). "
                    f"Severe record loss detected in hierarchical dataset."
                )

    else:
        # Standard tabular / relational dataset:
        if strict and retention_ratio < 0.70:
            loss_pct = (1.0 - retention_ratio) * 100
            raise OverCleaningViolation(
                f"Over-Cleaning Warning: Transformed dataset lost {loss_pct:.1f}% of records "
                f"({transformed_rows} rows remaining from {raw_rows} original rows). "
                f"Verify if blind dropna() or excessive deduplication was executed."
            )

    # 3. Numeric & Financial Conservation Check
    if pd is not None:
        try:
            raw_pdf = raw_df.to_pandas() if hasattr(raw_df, "to_pandas") else raw_df
            tx_pdf = transformed_df.to_pandas() if hasattr(transformed_df, "to_pandas") else transformed_df

            money_keywords = ["amount", "total", "price", "net", "gross", "debit", "credit", "balance", "cost", "sum"]
            raw_num_cols = [c for c in raw_pdf.columns if any(k in str(c).lower() for k in money_keywords)]
            tx_num_cols = [c for c in tx_pdf.columns if any(k in str(c).lower() for k in money_keywords)]

            if raw_num_cols and tx_num_cols:
                raw_sums = []
                for c in raw_num_cols:
                    clean_s = raw_pdf[c].astype(str).str.replace(",", "", regex=False).str.replace("$", "", regex=False).str.replace("₹", "", regex=False)
                    nums = pd.to_numeric(clean_s, errors="coerce").dropna()
                    if len(nums) > 0 and nums.sum() > 0:
                        raw_sums.append(nums.sum())

                tx_sums = []
                for c in tx_num_cols:
                    clean_s = tx_pdf[c].astype(str).str.replace(",", "", regex=False).str.replace("$", "", regex=False).str.replace("₹", "", regex=False)
                    nums = pd.to_numeric(clean_s, errors="coerce").dropna()
                    if len(nums) > 0:
                        tx_sums.append(nums.sum())

                if raw_sums:
                    max_raw = max(raw_sums)
                    max_tx = max(tx_sums) if tx_sums else 0.0
                    if max_raw > 100.0 and max_tx <= 0.0:
                        raise OverCleaningViolation(
                            f"Financial Conservation Violation: Raw dataset had substantial quantitative volume (sum ~{max_raw:,.2f}) "
                            f"but transformed dataset sum is 0.00. Quantitative columns were corrupted or zeroed out."
                        )
        except Exception as e:
            if isinstance(e, OverCleaningViolation):
                raise

    return True, f"Volumetric & retention safety verified ({transformed_rows:,} rows retained from {raw_rows:,})."


# =============================================================================
# PIPELINE GENERATION (.py and .ipynb)
# =============================================================================

def create_pipeline_file(dataset_dir: str, file_type: str = "py") -> str:
    """Creates an empty clean_pipeline.py or clean_pipeline.ipynb in the dataset directory."""
    os.makedirs(dataset_dir, exist_ok=True)
    if file_type.lower() in ("ipynb", "notebook", "2"):
        file_path = os.path.join(dataset_dir, "clean_pipeline.ipynb")
        notebook_content = {
            "cells": [
                {
                    "cell_type": "markdown",
                    "metadata": {},
                    "source": [
                        "# DeepAnalyze Data Transformation Pipeline\n",
                        "Generated by DeepAnalyze v4.0 Air-Gap Gateway."
                    ]
                }
            ],
            "metadata": {
                "language_info": {
                    "name": "python",
                    "version": "3.11"
                }
            },
            "nbformat": 4,
            "nbformat_minor": 5
        }
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(notebook_content, f, indent=1)
        return file_path
    else:
        file_path = os.path.join(dataset_dir, "clean_pipeline.py")
        header = (
            "# DeepAnalyze Data Transformation Pipeline\n"
            "# Generated by DeepAnalyze v4.0 Air-Gap Gateway\n"
            "import pandas as pd\n"
            "import numpy as np\n"
            "import polars as pl\n\n"
        )
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(header)
        return file_path


def append_code_to_pipeline(file_path: str, code_block: str) -> None:
    """Appends code block to clean_pipeline.py or as a new code cell to clean_pipeline.ipynb."""
    if not os.path.exists(file_path):
        return

    clean_code = code_block.strip()
    if not clean_code:
        return

    if file_path.endswith(".ipynb"):
        try:
            with open(file_path, "r", encoding="utf-8") as f:
                nb = json.load(f)

            source_lines = [line + "\n" for line in clean_code.splitlines()]
            new_cell = {
                "cell_type": "code",
                "execution_count": len(nb.get("cells", [])) + 1,
                "metadata": {},
                "outputs": [],
                "source": source_lines
            }
            nb.setdefault("cells", []).append(new_cell)

            with open(file_path, "w", encoding="utf-8") as f:
                json.dump(nb, f, indent=1)
        except Exception:
            pass
    else:
        with open(file_path, "a", encoding="utf-8") as f:
            f.write(f"\n# --- Pipeline Block ---\n{clean_code}\n")


# =============================================================================
# IN-MEMORY LIFO ROLLBACK STACK (5 SNAPSHOT LEVELS)
# =============================================================================

class RollbackManager:
    """Manages an in-memory LIFO snapshot stack (up to 5 levels) for zero-latency undo."""

    def __init__(self, max_depth: int = 5):
        self.max_depth = max_depth
        self._stacks: Dict[str, List[Any]] = defaultdict(list)

    def push(self, target_name: str, df: Any) -> None:
        """Pushes a clone/copy of the DataFrame (Polars or Pandas) onto the rollback stack."""
        if df is None:
            return
        stack = self._stacks[target_name]
        if len(stack) >= self.max_depth:
            stack.pop(0)

        if hasattr(df, "clone"):
            try:
                snapshot = df.clone()
            except Exception:
                snapshot = copy.deepcopy(df)
        elif hasattr(df, "copy"):
            try:
                snapshot = df.copy(deep=True)
            except Exception:
                snapshot = copy.deepcopy(df)
        else:
            try:
                snapshot = copy.deepcopy(df)
            except Exception:
                snapshot = df

        stack.append(snapshot)

    def pop(self, target_name: str) -> Optional[pl.DataFrame]:
        """Pops and returns the most recent DataFrame snapshot, or None if empty."""
        stack = self._stacks[target_name]
        if stack:
            return stack.pop()
        return None

    def clear(self, target_name: Optional[str] = None) -> None:
        if target_name:
            self._stacks[target_name].clear()
        else:
            self._stacks.clear()

    def depth(self, target_name: str) -> int:
        return len(self._stacks[target_name])


_GLOBAL_ROLLBACK = RollbackManager(max_depth=5)


def push_snapshot(target_name: str, df: Any) -> None:
    _GLOBAL_ROLLBACK.push(target_name, df)


def pop_snapshot(target_name: str) -> Optional[Any]:
    return _GLOBAL_ROLLBACK.pop(target_name)


def get_snapshot_depth(target_name: str) -> int:
    return _GLOBAL_ROLLBACK.depth(target_name)


# =============================================================================
# OUROBOROS SESSION FAILURE MEMORY (FOR --fix AUTONOMOUS REPAIR)
# =============================================================================

@dataclass
class ExecutionFailureContext:
    target_name: str
    code: str
    error: Any
    traceback_str: str
    timestamp: float
    columns: Optional[List[str]] = None
    shape: Optional[Tuple[int, int]] = None
    autopsy_report: Optional[str] = None


_LAST_EXECUTION_FAILURE: Optional[ExecutionFailureContext] = None


def record_execution_failure(
    target_name: str,
    code: str,
    error: Any,
    traceback_str: str,
    df: Optional[Any] = None,
    autopsy_report: Optional[str] = None
) -> ExecutionFailureContext:
    """Records the most recent execution failure for closed-loop Ouroboros --fix diagnosis."""
    global _LAST_EXECUTION_FAILURE
    cols = list(df.columns) if df is not None and hasattr(df, "columns") else None
    shape = tuple(df.shape) if df is not None and hasattr(df, "shape") else None

    _LAST_EXECUTION_FAILURE = ExecutionFailureContext(
        target_name=target_name,
        code=code,
        error=error,
        traceback_str=traceback_str,
        timestamp=time.time(),
        columns=cols,
        shape=shape,
        autopsy_report=autopsy_report
    )
    return _LAST_EXECUTION_FAILURE


def get_last_execution_failure() -> Optional[ExecutionFailureContext]:
    """Returns the most recent execution failure context, or None if clear."""
    return _LAST_EXECUTION_FAILURE


def clear_last_execution_failure() -> None:
    """Clears the failure memory once repaired."""
    global _LAST_EXECUTION_FAILURE
    _LAST_EXECUTION_FAILURE = None
