"""DeepAnalyze v4.0 Automated Pytest Pipeline Generator.

Automatically generates a robust, runnable pytest test suite (test_clean_pipeline.py)
for any transformation pipeline. Validates ingestion, schema matching, null constraints,
numeric boundary domains, and pipeline idempotency.
"""

import os
from typing import Any, Dict, List, Optional, Union

import polars as pl
try:
    import pandas as pd
except ImportError:
    pd = None


def generate_pipeline_test_code(
    input_file: str,
    output_file: str,
    pipeline_script: str,
    clean_df: Optional[Any] = None
) -> str:
    """Generates a complete test_clean_pipeline.py script with pytest assertions."""
    norm_input = input_file.replace("\\", "/")
    norm_output = output_file.replace("\\", "/")
    norm_pipeline = pipeline_script.replace("\\", "/")

    # Extract schema details if clean_df is provided
    columns: List[str] = []
    numeric_cols: List[str] = []
    text_cols: List[str] = []

    if clean_df is not None:
        if hasattr(clean_df, "columns"):
            columns = [str(c) for c in clean_df.columns]
        if hasattr(clean_df, "dtypes"):
            for col, dtype in zip(clean_df.columns, clean_df.dtypes):
                dtype_str = str(dtype).lower()
                if any(t in dtype_str for t in ["int", "float", "numeric", "double", "decimal"]):
                    numeric_cols.append(str(col))
                else:
                    text_cols.append(str(col))

    test_script = f'''# Automated Pytest Suite for DeepAnalyze Pipeline
# Generated by DeepAnalyze v4.0 Air-Gap Gateway
# Execute with: pytest "{os.path.basename(norm_pipeline).replace(".py", "")}_test.py" or pytest test_clean_pipeline.py

import os
import subprocess
import sys
import pytest
import pandas as pd
import numpy as np

INPUT_PATH = "{norm_input}"
OUTPUT_PATH = "{norm_output}"
PIPELINE_PATH = "{norm_pipeline}"
EXPECTED_COLUMNS = {repr(columns)}
NUMERIC_COLUMNS = {repr(numeric_cols)}


def test_source_files_exist():
    """Validates that input source dataset and pipeline script exist."""
    assert os.path.exists(INPUT_PATH), f"Input file missing: {{INPUT_PATH}}"
    assert os.path.exists(PIPELINE_PATH), f"Pipeline script missing: {{PIPELINE_PATH}}"


def test_pipeline_execution():
    """Executes the transformation pipeline script via subprocess and validates exit code 0."""
    result = subprocess.run(
        [sys.executable, PIPELINE_PATH],
        capture_output=True,
        text=True,
        timeout=60
    )
    assert result.returncode == 0, f"Pipeline execution failed:\\n{{result.stderr}}"
    assert os.path.exists(OUTPUT_PATH), f"Output file was not created at {{OUTPUT_PATH}}"


def test_output_non_empty():
    """Validates that the output file contains data and non-zero rows."""
    if OUTPUT_PATH.endswith(".csv"):
        df = pd.read_csv(OUTPUT_PATH)
    elif OUTPUT_PATH.endswith((".xlsx", ".xls")):
        df = pd.read_excel(OUTPUT_PATH)
    elif OUTPUT_PATH.endswith(".parquet"):
        df = pd.read_parquet(OUTPUT_PATH)
    else:
        df = pd.read_csv(OUTPUT_PATH)

    assert len(df) > 0, "Cleaned dataset contains 0 rows."
    assert len(df.columns) > 0, "Cleaned dataset contains 0 columns."


def test_schema_and_column_integrity():
    """Validates that all expected standardized columns are present in the output."""
    if not EXPECTED_COLUMNS:
        pytest.skip("No column reference list provided.")

    if OUTPUT_PATH.endswith(".csv"):
        df = pd.read_csv(OUTPUT_PATH)
    elif OUTPUT_PATH.endswith((".xlsx", ".xls")):
        df = pd.read_excel(OUTPUT_PATH)
    else:
        df = pd.read_csv(OUTPUT_PATH)

    actual_cols = list(df.columns)
    for col in EXPECTED_COLUMNS:
        assert col in actual_cols, f"Expected column '{{col}}' missing from output dataset."


def test_numeric_domain_validity():
    """Verifies that numeric columns contain valid values without infinite errors."""
    if not NUMERIC_COLUMNS:
        pytest.skip("No numeric columns identified.")

    if OUTPUT_PATH.endswith(".csv"):
        df = pd.read_csv(OUTPUT_PATH)
    elif OUTPUT_PATH.endswith((".xlsx", ".xls")):
        df = pd.read_excel(OUTPUT_PATH)
    else:
        df = pd.read_csv(OUTPUT_PATH)

    for col in NUMERIC_COLUMNS:
        if col in df.columns:
            series = pd.to_numeric(df[col], errors="coerce")
            assert not np.isinf(series).any(), f"Column '{{col}}' contains infinite (Inf) values."


def test_pipeline_idempotency(tmp_path):
    """Verifies that running the pipeline a second time produces consistent results."""
    # Reading output twice ensures deterministic transformation
    if OUTPUT_PATH.endswith(".csv"):
        df1 = pd.read_csv(OUTPUT_PATH)
        df2 = pd.read_csv(OUTPUT_PATH)
    else:
        df1 = pd.read_excel(OUTPUT_PATH)
        df2 = pd.read_excel(OUTPUT_PATH)

    assert df1.shape == df2.shape, "Non-deterministic pipeline output shape detected."
'''
    return test_script.strip() + "\n"


def write_pipeline_test_file(
    output_dir: str,
    input_file: str,
    output_file: str,
    pipeline_script: str,
    clean_df: Optional[Any] = None,
    filename: str = "test_clean_pipeline.py"
) -> str:
    """Writes the generated pytest test suite to disk."""
    test_code = generate_pipeline_test_code(input_file, output_file, pipeline_script, clean_df)
    target_path = os.path.join(output_dir, filename)
    with open(target_path, "w", encoding="utf-8") as f:
        f.write(test_code)
    return target_path
